pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: sdk
    version: 2.2.x

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- script: dotnet test NeoToCosmos.Unit.Tests --logger trx
  displayName: 'Unit Tests'

# - task: PowerShell@2
#   displayName: 'Enable LCOW support on Docker'
#   inputs:
#     targetType: filePath
#     filePath: .\devops\enable-docker-lcow.ps1

# - task: PowerShell@2
#   displayName: 'Run neo-to-cosmos'
#   inputs:
#     targetType: filePath
#     filePath: .\devops\neo-to-cosmos.ps1

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'