pool:
  vmImage: windows-latest

variables:
  buildConfiguration: Release

steps:
- task: UseDotNet@2
  displayName: Install .NET Core SDK
  inputs:
    packageType: sdk
    version: 3.1.x

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    arguments: --configuration $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    arguments: --configuration $(buildConfiguration) --no-restore

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    projects: "**/*(NeoToCosmos.Unit.Tests.csproj)"
    nobuild: true
    arguments: --configuration $(buildConfiguration)
    publishTestResults: true

# - task: PowerShell@2
#   displayName: 'Run neo-to-cosmos'
#   inputs:
#     targetType: filePath
#     filePath: .\devops\neo-to-cosmos.ps1