pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:    
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- script: dotnet test NeoToCosmos.Unit.Tests --logger trx
  displayName: 'Unit Tests'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'